version: '3'

services:
    web:
        build: .
        command: python3 manage.py runserver 0.0.0.0:8000 
        ports:
            - 8000:8000

    rasa:
        image: rasa/rasa:1.10.7-full
        ports:
            - 5005:5005            
        volumes:
            - ./:/PNECBS
        command:
            - run

    action-server:
        image: rasa/rasa-sdk:1.10.2
        volumes:
            - ./actions/actions.py:/PNECBS/actions/actions.py
        ports:
            - 5055:5055                        
