version: '3'

services:
    rasa:
        image: rasa/rasa:1.10.7-full
        ports:
            - 5005:5005            
        volumes:
            - ./:/PNECBS
        command:
            - run

    action-server:
        image: rasa/rasa-sdk:1.10.2
        volumes:
            - ./actions/:/PNECBS/
        ports:
            - 5055:5055   
