# Generated by Django 3.1.3 on 2020-12-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_content_specs'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='usern',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
